package com.educom.db.educom_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE AddressBase PLEASE EDIT ../Address.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Address object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.educom.db.educom_db.entity.Address;

public class AddressBase implements RowMapper<Address>{
	
	private Long _id;
	
	// Attributes
    private Double Country;
    private String Village;
    private String district;
	
	
	
	@Override
	public Address mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Address obj = new Address();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setCountry(rs.getDouble("Country"));
			obj.setVillage(rs.getString("Village"));
			obj.setDistrict(rs.getString("district"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public Double getCountry() {
		return Country;
	}


	public void setCountry(Double Country) {
		this.Country = Country;
	}
	public String getVillage() {
		return Village;
	}


	public void setVillage(String Village) {
		this.Village = Village;
	}
	public String getDistrict() {
		return district;
	}


	public void setDistrict(String district) {
		this.district = district;
	}
	
    
    
    
    
}