package com.educom.db.educom_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE ContactBase PLEASE EDIT ../Contact.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Contact object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.educom.db.educom_db.entity.Contact;

public class ContactBase implements RowMapper<Contact>{
	
	private Long _id;
	
	// Attributes
    private String RefFirstPhoneNo;
    private String firstPhoneNo;
    private String secondPhoneNo;
    private String socialMedia;
	
	
	
	@Override
	public Contact mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Contact obj = new Contact();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setRefFirstPhoneNo(rs.getString("RefFirstPhoneNo"));
			obj.setFirstPhoneNo(rs.getString("firstPhoneNo"));
			obj.setSecondPhoneNo(rs.getString("secondPhoneNo"));
			obj.setSocialMedia(rs.getString("socialMedia"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getRefFirstPhoneNo() {
		return RefFirstPhoneNo;
	}


	public void setRefFirstPhoneNo(String RefFirstPhoneNo) {
		this.RefFirstPhoneNo = RefFirstPhoneNo;
	}
	public String getFirstPhoneNo() {
		return firstPhoneNo;
	}


	public void setFirstPhoneNo(String firstPhoneNo) {
		this.firstPhoneNo = firstPhoneNo;
	}
	public String getSecondPhoneNo() {
		return secondPhoneNo;
	}


	public void setSecondPhoneNo(String secondPhoneNo) {
		this.secondPhoneNo = secondPhoneNo;
	}
	public String getSocialMedia() {
		return socialMedia;
	}


	public void setSocialMedia(String socialMedia) {
		this.socialMedia = socialMedia;
	}
	
    
    
    
    
}