package com.educom.db.educom_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE TeacherBase PLEASE EDIT ../Teacher.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Teacher object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.educom.db.educom_db.entity.Teacher;

public class TeacherBase implements RowMapper<Teacher>{
	
	private Long _id;
	
	// Attributes
    private String address;
    private String administration;
    private String contact;
    private Date dob;
    private String email;
    private String firstName;
    private String gender;
    private String lastName;
    private String nin;
	
	// Relations subjectId
	private String subjectId;
	
	
	
	@Override
	public Teacher mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Teacher obj = new Teacher();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setAddress(rs.getString("address"));
			obj.setAdministration(rs.getString("administration"));
			obj.setContact(rs.getString("contact"));
			obj.setDob(rs.getDate("dob"));
			obj.setEmail(rs.getString("email"));
			obj.setFirstName(rs.getString("firstName"));
			obj.setGender(rs.getString("gender"));
			obj.setLastName(rs.getString("lastName"));
			obj.setNin(rs.getString("nin"));
			
        	
        	// Relations 1:m subjectId
			obj.setSubjectId(rs.getString("subjectId"));
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getAddress() {
		return address;
	}


	public void setAddress(String address) {
		this.address = address;
	}
	public String getAdministration() {
		return administration;
	}


	public void setAdministration(String administration) {
		this.administration = administration;
	}
	public String getContact() {
		return contact;
	}


	public void setContact(String contact) {
		this.contact = contact;
	}
	public Date getDob() {
		return dob;
	}


	public void setDob(Date dob) {
		this.dob = dob;
	}
	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}
	public String getFirstName() {
		return firstName;
	}


	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getGender() {
		return gender;
	}


	public void setGender(String gender) {
		this.gender = gender;
	}
	public String getLastName() {
		return lastName;
	}


	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getNin() {
		return nin;
	}


	public void setNin(String nin) {
		this.nin = nin;
	}
	
    
    // Relations 1:m subjectId
	public String getSubjectId() {
		return subjectId;
	}

	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}
    
    
    
    
}