
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// ADDRESS
export const RESET_ADDRESS = "RESET_ADDRESS";

// ATTENDANCE
export const RESET_ATTENDANCE = "RESET_ATTENDANCE";

// CLASS
export const RESET_CLASS = "RESET_CLASS";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const FINDBYCLASSSUBJECT_CLASS_SUCCESS = "FINDBYCLASSSUBJECT_CLASS_SUCCESS";
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS";
export const LIST_CLASS_SUCCESS = "LIST_CLASS_SUCCESS";
export const UPDATE_CLASS_SUCCESS = "UPDATE_CLASS_SUCCESS";

// CONTACT
export const RESET_CONTACT = "RESET_CONTACT";

// MARKS
export const RESET_MARKS = "RESET_MARKS";

// PARENT
export const RESET_PARENT = "RESET_PARENT";

// REPORTCARD
export const RESET_REPORTCARD = "RESET_REPORTCARD";

// SCHOOL
export const RESET_SCHOOL = "RESET_SCHOOL";

// SCHOOL
export const RESET_SCHOOL = "RESET_SCHOOL";

// STUDENT
export const RESET_STUDENT = "RESET_STUDENT";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const LIST_STUDENT_SUCCESS = "LIST_STUDENT_SUCCESS";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";

// SUBJECT
export const RESET_SUBJECT = "RESET_SUBJECT";
export const CREATE_SUBJECT_SUCCESS = "CREATE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS";
export const LIST_SUBJECT_SUCCESS = "LIST_SUBJECT_SUCCESS";
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS";

// TEACHER
export const RESET_TEACHER = "RESET_TEACHER";
export const CREATE_TEACHER_SUCCESS = "CREATE_TEACHER_SUCCESS";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const FINDBYSUBJECTID_TEACHER_SUCCESS = "FINDBYSUBJECTID_TEACHER_SUCCESS";
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";
export const LIST_TEACHER_SUCCESS = "LIST_TEACHER_SUCCESS";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";

// USER
export const RESET_USER = "RESET_USER";
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
